version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: suiver-postgres
    restart: always
    environment:
      POSTGRES_DB: db_de5ded4f
      POSTGRES_USER: user_7afcbc4f
      POSTGRES_PASSWORD: 6204e4bc3198d40f5e626515a41ce246
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  suiver-backend:
    build: .
    container_name: suiver-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user_7afcbc4f:6204e4bc3198d40f5e626515a41ce246@db.pxxl.pro:37151/db_de5ded4f
    depends_on:
      - postgres
    command: npm run start:dev

volumes:
  postgres_data:
