version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: suiver-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  suiver-backend:
    build: .
    container_name: suiver-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TOKEN_EXPIRY: ${JWT_ACCESS_TOKEN_EXPIRY}
      USD_TO_NGN_RATE: ${USD_TO_NGN_RATE}
      SOLANA_RPC_URL: https://api.mainnet-beta.solana.com
      ETH_RPC_URL: https://mainnet.infura.io/v3/YOUR_PROJECT_ID
    depends_on:
      - postgres
    command: npm run start:dev

volumes:
  postgres_data:

      