import { PrismaService } from '../prisma/prisma.service';
import { CreatePaymentLinkDto } from '../user/dto/create-payment-link.dto';
export declare class PaymentLinksService {
    private prisma;
    constructor(prisma: PrismaService);
    create(userId: string, dto: CreatePaymentLinkDto): Promise<{
        amount: number | null;
        id: string;
        userId: string;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        status: import(".prisma/client").$Enums.PaymentLinkStatus;
        description: string | null;
        autoTransferBank: boolean;
        slug: string;
        title: string;
        invoiceNumber: string | null;
        dueDate: Date | null;
        acceptedMethods: import(".prisma/client").$Enums.PaymentLinkPayMethod;
        acceptedAssets: string[];
        depositWalletId: string | null;
        bankInstructions: string | null;
        expiresAt: Date | null;
        autoConvertToNgn: boolean;
        settleBankId: string | null;
    }>;
    findByCode(code: string): Promise<{
        amount: number | null;
        id: string;
        userId: string;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        status: import(".prisma/client").$Enums.PaymentLinkStatus;
        description: string | null;
        autoTransferBank: boolean;
        slug: string;
        title: string;
        invoiceNumber: string | null;
        dueDate: Date | null;
        acceptedMethods: import(".prisma/client").$Enums.PaymentLinkPayMethod;
        acceptedAssets: string[];
        depositWalletId: string | null;
        bankInstructions: string | null;
        expiresAt: Date | null;
        autoConvertToNgn: boolean;
        settleBankId: string | null;
    }>;
    findByUserId(userId: string): Promise<{
        amount: number | null;
        id: string;
        userId: string;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        status: import(".prisma/client").$Enums.PaymentLinkStatus;
        description: string | null;
        autoTransferBank: boolean;
        slug: string;
        title: string;
        invoiceNumber: string | null;
        dueDate: Date | null;
        acceptedMethods: import(".prisma/client").$Enums.PaymentLinkPayMethod;
        acceptedAssets: string[];
        depositWalletId: string | null;
        bankInstructions: string | null;
        expiresAt: Date | null;
        autoConvertToNgn: boolean;
        settleBankId: string | null;
    }[]>;
    delete(userId: string, id: number): Promise<{
        success: boolean;
        message: string;
    }>;
    update(userId: string, id: number, dto: Partial<CreatePaymentLinkDto>): Promise<{
        amount: number | null;
        id: string;
        userId: string;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        status: import(".prisma/client").$Enums.PaymentLinkStatus;
        description: string | null;
        autoTransferBank: boolean;
        slug: string;
        title: string;
        invoiceNumber: string | null;
        dueDate: Date | null;
        acceptedMethods: import(".prisma/client").$Enums.PaymentLinkPayMethod;
        acceptedAssets: string[];
        depositWalletId: string | null;
        bankInstructions: string | null;
        expiresAt: Date | null;
        autoConvertToNgn: boolean;
        settleBankId: string | null;
    }>;
    createWithCurrency(userId: string, dto: CreatePaymentLinkDto, currency?: string): Promise<{
        amount: number | null;
        id: string;
        userId: string;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        status: import(".prisma/client").$Enums.PaymentLinkStatus;
        description: string | null;
        autoTransferBank: boolean;
        slug: string;
        title: string;
        invoiceNumber: string | null;
        dueDate: Date | null;
        acceptedMethods: import(".prisma/client").$Enums.PaymentLinkPayMethod;
        acceptedAssets: string[];
        depositWalletId: string | null;
        bankInstructions: string | null;
        expiresAt: Date | null;
        autoConvertToNgn: boolean;
        settleBankId: string | null;
    }>;
}
