import { PrismaService } from '../prisma/prisma.service';
import { CreateUserDto, LoginDto } from './dto/auth.dto';
import { UpdateUserDto, UpdateKycDto, UpdatePinDto, UpdateBiometricDto } from './dto/update-user.dto';
import { JwtService } from '@nestjs/jwt';
import { KycDto } from './dto/kyc.dto';
export declare class UsersService {
    private prisma;
    private jwtService;
    constructor(prisma: PrismaService, jwtService: JwtService);
    signup(dto: CreateUserDto): Promise<{
        user: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            phone: string;
            email: string | null;
            username: string | null;
            passwordHash: string;
            transactionPinHash: string | null;
            fullName: string;
            avatarInitials: string | null;
            kycStatus: import(".prisma/client").$Enums.KycStatus;
            kycProvider: import(".prisma/client").$Enums.KycProvider | null;
            kycSmileRef: string | null;
            kycQoreRef: string | null;
            bvnHash: string | null;
            autoConvertGlobal: boolean;
            autoTransferBank: boolean;
            defaultBankId: string | null;
            dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
            dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
            limitResetAt: Date | null;
            referralCode: string;
            referredById: string | null;
            isDeleted: boolean;
        };
        token: string;
    }>;
    login(dto: LoginDto): Promise<{
        user: {
            id: string;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            phone: string;
            email: string | null;
            username: string | null;
            passwordHash: string;
            transactionPinHash: string | null;
            fullName: string;
            avatarInitials: string | null;
            kycStatus: import(".prisma/client").$Enums.KycStatus;
            kycProvider: import(".prisma/client").$Enums.KycProvider | null;
            kycSmileRef: string | null;
            kycQoreRef: string | null;
            bvnHash: string | null;
            autoConvertGlobal: boolean;
            autoTransferBank: boolean;
            defaultBankId: string | null;
            dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
            dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
            limitResetAt: Date | null;
            referralCode: string;
            referredById: string | null;
            isDeleted: boolean;
        };
        token: string;
    }>;
    findOne(id: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    }>;
    findByEmail(email: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    } | null>;
    findByTag(tag: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    } | null>;
    update(id: string, dto: UpdateUserDto): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    }>;
    updateKyc(id: string, dto: UpdateKycDto): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    }>;
    updatePin(id: string, dto: UpdatePinDto): Promise<{
        success: boolean;
    }>;
    updateBiometric(id: string, dto: UpdateBiometricDto): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    }>;
    setUserTag(userId: string, desiredTag: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    }>;
    submitKyc(userId: string, dto: KycDto): Promise<{
        id: string;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
    }>;
    getReferrals(id: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    }[]>;
    delete(id: string): Promise<{
        id: string;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        phone: string;
        email: string | null;
        username: string | null;
        passwordHash: string;
        transactionPinHash: string | null;
        fullName: string;
        avatarInitials: string | null;
        kycStatus: import(".prisma/client").$Enums.KycStatus;
        kycProvider: import(".prisma/client").$Enums.KycProvider | null;
        kycSmileRef: string | null;
        kycQoreRef: string | null;
        bvnHash: string | null;
        autoConvertGlobal: boolean;
        autoTransferBank: boolean;
        defaultBankId: string | null;
        dailySellLimitUsd: import("@prisma/client/runtime/library").Decimal;
        dailySoldUsd: import("@prisma/client/runtime/library").Decimal;
        limitResetAt: Date | null;
        referralCode: string;
        referredById: string | null;
        isDeleted: boolean;
    }>;
}
