import { PrismaService } from '../prisma/prisma.service';
import { DepositDto, WithdrawDto, SendDto, UpdateDto } from '../user/dto/wallet.dto';
export declare class WalletService {
    private prisma;
    constructor(prisma: PrismaService);
    findByUserId(userId: string, currency?: string): Promise<{
        balance: number;
        id: string;
        userId: string;
        address: string;
        chain: import(".prisma/client").$Enums.Chain;
        asset: string;
        tatumAccountId: string | null;
        tatumSubId: string | null;
        autoConvert: boolean;
        autoConvertTo: import(".prisma/client").$Enums.AutoConvertTarget | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getBalance(userId: string, currency?: string): Promise<{
        balance: number;
        currency: any;
    }>;
    findAllByUserId(userId: string): Promise<{
        balance: number;
        id: string;
        userId: string;
        address: string;
        chain: import(".prisma/client").$Enums.Chain;
        asset: string;
        tatumAccountId: string | null;
        tatumSubId: string | null;
        autoConvert: boolean;
        autoConvertTo: import(".prisma/client").$Enums.AutoConvertTarget | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    deposit(userId: string, dto: DepositDto): Promise<{
        balance: number;
        id: string;
        userId: string;
        address: string;
        chain: import(".prisma/client").$Enums.Chain;
        asset: string;
        tatumAccountId: string | null;
        tatumSubId: string | null;
        autoConvert: boolean;
        autoConvertTo: import(".prisma/client").$Enums.AutoConvertTarget | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    withdraw(userId: string, dto: WithdrawDto): Promise<{
        balance: number;
        id: string;
        userId: string;
        address: string;
        chain: import(".prisma/client").$Enums.Chain;
        asset: string;
        tatumAccountId: string | null;
        tatumSubId: string | null;
        autoConvert: boolean;
        autoConvertTo: import(".prisma/client").$Enums.AutoConvertTarget | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    send(userId: string, dto: SendDto): Promise<{
        balance: number;
        id: string;
        userId: string;
        address: string;
        chain: import(".prisma/client").$Enums.Chain;
        asset: string;
        tatumAccountId: string | null;
        tatumSubId: string | null;
        autoConvert: boolean;
        autoConvertTo: import(".prisma/client").$Enums.AutoConvertTarget | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(userId: string, currency: string, dto: UpdateDto): Promise<{
        balance: number;
        id: string;
        userId: string;
        address: string;
        chain: import(".prisma/client").$Enums.Chain;
        asset: string;
        tatumAccountId: string | null;
        tatumSubId: string | null;
        autoConvert: boolean;
        autoConvertTo: import(".prisma/client").$Enums.AutoConvertTarget | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getTransactionHistory(userId: string, currency?: string): Promise<{
        amount: number;
        id: string;
        userId: string;
        createdAt: Date;
        updatedAt: Date;
        cryptoAsset: string;
        cryptoAmount: import("@prisma/client/runtime/library").Decimal;
        ngnAmount: import("@prisma/client/runtime/library").Decimal;
        feeAmount: import("@prisma/client/runtime/library").Decimal;
        feePercent: import("@prisma/client/runtime/library").Decimal;
        lockedRateNgn: import("@prisma/client/runtime/library").Decimal;
        depositAddress: string;
        txHash: string | null;
        confirmations: number;
        payoutProvider: import(".prisma/client").$Enums.PayoutProvider | null;
        payoutReference: string | null;
        payoutSentAt: Date | null;
        status: import(".prisma/client").$Enums.TxStatus;
        failureReason: string | null;
        isAutoConvert: boolean;
        walletId: string;
        bankAccountId: string;
        rateLockId: string;
    }[]>;
    createWallet(userId: string, currency?: string): Promise<{
        balance: number;
        id: string;
        userId: string;
        address: string;
        chain: import(".prisma/client").$Enums.Chain;
        asset: string;
        tatumAccountId: string | null;
        tatumSubId: string | null;
        autoConvert: boolean;
        autoConvertTo: import(".prisma/client").$Enums.AutoConvertTarget | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
}
